#main:
#  - name: Home
#    identifier: 
#    weight: 5
#    url: /home/
#    params:
#      header: The HB support community.
#      icon:
#        vendor: font-awesome-solid
#        name: headset
#
#  - name: Wiki
#    parent: 
#    url: /docs/
#    weight: 10
#    params:
#      icon:
#        vendor: bs
#        name: book
#        className: text-primary
#      description: The documentation.
#
#  - name: Foto
#    parent: 
#    url: /gallery/
#    params:
#      icon:
#        vendor: fab
#        name: github
#      description: The code repository.
#
#  - name: Blog
#    parent: 
#    url: /blog/
#    weight: 30
#    params:
#      icon:
#        vendor: font-awesome-regular
#        name: comments
#        color: green
#      description: Ask questions and share your ideas.
#
#  - name: Kontakt
#    parent: 
#    url: https://github.com/orgs/hbstack/discussions/new?category=issues-and-bugs
#    weight: 40
#    params:
#      icon:
#        vendor: font-awesome-solid
#        name: bug
#        color: red
#      description: Tell us about a bug or issue.